# Generated by Django 3.2 on 2023-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodgram',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='password',
            field=models.CharField(max_length=254, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
